### PR TITLE
Added Tests for revise! and fixed a few errors

### PR DESCRIPTION
**Pull request by gautamrege**
revise! was failing and there were not test cases for it.. added them

Also a few errors fixed:
- clear_persistence option not required 
- Factory#build should not specify attribute protection.

### CODE REVIEW

**Comment by simi** [comment]
Thanks for fixes @gautamrege! Some tests are failing now, I'll try to figure out why. :heart_eyes_cat:

**Comment by gautamrege** [comment]
There are couple of tests (un-related to my commits) that are failing on local..pushed the changes nevertheless :smiling_imp: These were the tests when not using default database. am investigating.

**Comment by simi** [comment]
@gautamrege I think it is related to https://github.com/mongoid/mongoid/commit/0a486e09158e6fe2ff8834253cb6091d575fd18d.

**Comment by simi** [comment]
@gautamrege any news?

**Comment by gautamrege** [comment]
Heh! Got stuck with some work - looking into this now.

**Comment by gautamrege** [comment]
@simi This should fix things. Let me know your thoughts.

**Comment by simi** [comment]
@gautamrege sorry. I missed your comment. Looks good! Awesome work @gautamrege.

**Comment by gautamrege** [comment]
cool!

**Comment by simi** [comment]
I added you into contributors list. I'll give you rubygems access once I'll release this if you're interested.

**Comment by gautamrege** [comment]
Awesome - I can surely help in supporting this.

**Pull request merged**
